### PR TITLE
created a config database for travis

### PR DESCRIPTION
**Pull request by adin234**
it still fails on .11 though. mocha --harmony test

### CODE REVIEW

**Comment by adin234** [comment]
https://travis-ci.org/adin234/mysql/jobs/48525392

**Comment by cblanquera** [comment]
@cjzamora can you validate and soft merge (if necessary) aldrin's pull request ? Our travis tests were already passing ...

**Comment by cblanquera** [comment]
@adin234 Might have to buy you lunch.

**Comment by cjzamora** [comment]
@cblanquera Yea sure, gonna validate if the test are good. Then merge it after.

**Comment by cjzamora** [comment]
@adin234 @cblanquera Travis test are already passing, the problem is in harmony flag, which in newer node version must be --harmony-proxies instead of --harmony, also i remove the password for the test, default root travis account does not have password. Please refer to this, 

24ea12ebb90b2e03bfb08f86047a045f39809abb
637a14b18f75b778efba6507e04683b6faa898d4
654e2e063edbbbfb7cf6eaa8ab9da2b8cbeb967a

**Comment by adin234** [comment]
yes, your test failures before was only because of the wrong password on your tests files. thats why i suggested on creating a database.js file which contains your database configurations for you to just use

```
var database = require(__dirname + '/database')();

instead of

```
var database = mysql('127.0.0.1', 3306, 'edenjs_test', 'root');

on every test you create :).

good to know the builds are passing now :)

**Pull request closed without merging**
